version: '3'
services:
  maindeck_no_redirect:
    image: maindeck/nginx-redirect
    build: .
    restart: always
    networks:
      - public
    environment:
      - SERVER_REDIRECT=${REDIRECT_DEST:?}
    deploy:
      labels:
        - traefik.frontend.rule=Host:${REDIRECT_SOURCE:?}
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=public
        - traefik.docker.network=public
networks:
  public:
    external: true